<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\File;
use PhpParser\Node\Stmt\Static_;

class Post extends Model
{
    protected $guarded =[]; //empty guarded means no guarding

     public function user()
     {
         return $this->belongsTo(User::class,"user_id");
     }

     protected static function boot()
     {
         parent::boot(); // TODO: Change the autogenerated stub

         Static::deleting(function($post){
             File::delete(public_path("storage/{$post->image}"));
         });
     }
}
